spring:
  application:
    name: diplom
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret:  ${JWT_ENCODER_SECRET:b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e}
  token:
    refresh:
      expiration: ${REFRESH_TOKEN_EXPIRATION:7}
    access:
      expiration: ${ACCESS_TOKEN_EXPIRATION:3600}
    issuer: ${TOKEN_ISSUER:server}